### PR TITLE
CI configs & test improvements

### PR DESCRIPTION
**Pull request by acampbel**
Add ci configs for CircleCI and Azure pipelines. Also, use more specific test apis for better failure diagnostics. Note you will need to sign up for CircleCI and/or Azure Pipelines to actually use the configs. CI FTW!

### CODE REVIEW

**Review by gehrhorn — APPROVED** [review]
Thanks @acampbel

**Comment by acampbel** [comment]
> Thanks @acampbel

My pleasure!

Did you sign up and apply either CircleCI and/or Azure Pipelines to run the CI? You can do this via GitHub apps or directly with the services themselves. 

If so, consider adding a badge(s) of the results to the readme.

**Comment by gehrhorn** [comment]
No, I haven't done that before and was going to look up instructions or ping you to see if there was a doc for complete beginners :-)

**Comment by gehrhorn** [comment]
@acampbel I got it working. Thanks again
image

**Pull request merged**
